### ISSUE TITLE
Readme not up to date, describing another tool

### ISSUE THREAD

**Issue by worming004** [AClerbois/sln.add.csproj#1]
The read me describe the use of sln tool.
Expected : behavior of _dotnet-addcsproj_ command

**Comment by worming004** [comment]
Also, the solution is using .net core 3.1. The readme refer to .net core 2.1

**Comment by AClerbois** [comment]
Hello @worming004 ,

Thank you for your feedbacks, I fixed now .

You rocks ;-) 

See you

Adri.
